#import "../lib.typ": *

#show: manual.with(title: "Televoto — General Overview", lang: "en")

#cover(
  icon: "🗳  📱  🏆  📊",
  eyebrow: "Live voting platform for events",
  title: "Televoto",
  subtitle: [
    Turn your audience into a jury. Real-time voting, live rankings, and a grand Final Ranking
    reveal — no app to install.
  ],
  meta: "General overview — document for prospective adopters",
)

#section-title[What is Televoto]

Televoto is a web platform designed for organizers running *events with live voting*: talent
shows, artistic or sports competitions, hackathons, festivals, corporate or school contests. It
replaces paper ballots, spreadsheets, and manual counting with a real-time digital system,
accessible from a smartphone via a simple link or QR code — no app to download, no account to
create for voters.

#section-title[How it works, in 3 phases]

#card-grid(
  cols: 3,
  card(icon: "⚙️", title: "1 · Set up the event")[
    The organizer creates the event, adds the candidates/competitors, and generates the access
    codes for judges and the public.
  ],
  card(icon: "📲", title: "2 · Live voting")[
    Judges and the public receive a link or a QR code, open the page on their phone, and assign
    a score to each candidate.
  ],
  card(icon: "🏆", title: "3 · Ranking and reveal")[
    The final score is calculated automatically and revealed with a dedicated scenic effect:
    the Final Ranking.
  ],
)

#section-title[Key features]

#card-grid(
  cols: 2,
  card(icon: "⚖️", title: "Dual voting channel")[
    Qualified jury (weighted vote) and general public, combined with customizable weights per
    event (e.g. 70% jury / 30% public).
  ],
  card(icon: "🔐", title: "Single-use voting codes")[
    Every voter receives a unique code shared via link or QR, valid for one vote per candidate:
    no duplicate votes.
  ],
  card(icon: "📡", title: "Live dashboard")[
    The organizer sees in real time how many codes have been used and how voting is
    progressing, without needing to reload the page.
  ],
  card(icon: "🗂", title: "Multi-event management")[
    A central panel to organize multiple events, each with its own candidates, codes, and
    password, fully isolated from one another. Wrapped-up events archive in one click and can be
    cloned to restart from an already-ready format.
  ],
  card(icon: "📈", title: "Configurable scoring")[
    Weighted average between jury and public, with an optional "trimmed mean" to reduce the
    impact of anomalous or outlier votes.
  ],
  card(icon: "🎉", title: "Final Ranking")[
    A final-ranking reveal screen designed for the event's key moment, in front of the audience.
  ],
)

#pagebreak()

#section-title[Who it's for]

Televoto adapts to any live event where a vote needs to be collected from multiple people,
quickly and transparently:

#chip-row((
  "🎤 Talent shows",
  "🏅 Competitions and contests",
  "💻 Hackathons",
  "🎭 Festivals and cultural events",
  "🏢 Corporate events",
  "🏫 School contests",
  "🎶 Music contests",
  "🍕 Fairs and fêtes",
))

#suggerimento(title: "Zero friction for voters")[
  Just open a link or scan a QR code from your phone. No registration, no personal data
  required, no app to install.
]

#section-title[Security and reliability]

#card-grid(
  cols: 3,
  card(icon: "🔑", title: "Separate access levels")[
    Dedicated password for the general administrator and for each individual event organizer.
  ],
  card(icon: "🎟", title: "Protected codes")[
    Voting codes are opaque and single-use, stored only in encrypted form: never in plain text
    in the system.
  ],
  card(icon: "🕵", title: "No tracking")[
    Voters are not profiled: no personal data or device identifier is collected.
  ],
)

#section-title[Why choose it]

#card-grid(
  cols: 2,
  card(icon: "⚡", title: "Ready in minutes")[
    Creating an event, adding candidates, and generating codes takes just a few guided steps.
  ],
  card(icon: "📱", title: "Browser only, no app")[
    Works on any smartphone or tablet with a connection, no installation required.
  ],
  card(icon: "🧮", title: "Automatic counting")[
    Zero calculation errors: the final score is generated by the system according to
    transparent, configurable rules.
  ],
  card(icon: "🎬", title: "Guaranteed showstopper moment")[
    The Final Ranking turns the results announcement into a show moment designed for the
    audience in the room.
  ],
)

#pagebreak()

#v(1fr)
#align(center, block(width: 85%, {
  set align(center)
  text(22pt, "🗳  🏆  📱")
  v(1em)
  text(26pt, weight: 700, fill: tv.ink)[Ready to bring live voting to your next event?]
  v(0.8em)
  text(14pt, fill: tv.ink-soft)[
    Televoto is the solution for anyone who wants to engage the audience and the jury in real
    time, with a system that's simple, secure, and built for the drama of the verdict moment.
  ]
}))
#v(1fr)
